name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # 改为你的主分支名称，通常是 main 或 master

jobs:
  build-and-deploy-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'  # 启用 npm 缓存

      # ② 清除旧依赖（避免缓存导致的安装问题）
      - name: Clean old dependencies
        run: |
          rm -rf node_modules
          rm -rf playwright-report/


      - name: Install dependencies
        run: npm ci --force  # --force 强制重新下载所有依赖

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages  # 可选，指定发布到的分支，默认为 gh-pages
          force_orphan: true  # 可选，强制创建孤立分支

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # ⑤ 运行测试（无需再手动安装浏览器，官方 Action 已处理）
      - name: Run Playwright tests
        run: cd playwright && npx playwright test --project custom --reporter=html --trace on # 生成 HTML 报告和追踪

      # ⑥ 上传报告（保持原逻辑）
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30